### ISSUE TITLE
Weight shape mismatch

### ISSUE THREAD

**Issue by byungokhan** [LLaVA-VL/LLaVA-NeXT#187]
I finetuned "llava-onevision-qwen2-7b-si" using my custom data.

After the fine-tuning process, I tried to inference using my finetuned model.

But, when I use the load_pretrained_model function,  I met an error like this:

ValueError: Trying to set a tensor of shape torch.Size([152064, 3584]) in "weight" (which has shape torch.Size([151936, 3584])), this looks incorrect.

128 dimension is missing.

Can you help me about this problem?

**Comment by ChipsICU** [comment]
I do have the same problem, try to use this.
overwrite_config = {'tie_word_embeddings': True, 'use_cache': True, "vocab_size": 152064}

**Comment by byungokhan** [comment]
But, another problem is here:
----------------------------------------------------------
    self.config.text_config.vocab_size = vocab_size
AttributeError: 'dict' object has no attribute 'vocab_size'

**Comment by ChipsICU** [comment]
if this work for you, plz let me know, thks.

**Comment by byungokhan** [comment]
Thanks.
It does work with transformers==4.40.0 (downgraded)
But, the inference result is completely wrong, , as if there is an issue with the tokenizer.
Like this;
  ["duction less1 leaving111 RightRing剧烈 numericaltool'),\nige less lesstool11tooltooltooltooltool lesstooltooltool tractor2namesCharlestooltooltooltooltooltooltooltooltooltooltooltooltooltooltooltooltooltooltooltooltooltooltooltooltooltool Deadline(line Browseelsing Lans哪些、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、"]

How do you think?

**Comment by ChipsICU** [comment]
@byungokhan Now we have the same problem, LOL!

**Comment by ChipsICU** [comment]
BTW, 0.5b works fine.

**Comment by byungokhan** [comment]
In my case, 0.5b doesn't work, resulting completely wrong sentences generated.

**Comment by byungokhan** [comment]
Any suggestion for this problem?

**Comment by byungokhan** [comment]
@ChipsICU This works for 7b.
overwrite_config = {'tie_word_embeddings': False, 'use_cache': True, "vocab_size": 152064}

**Comment by ChipsICU** [comment]
Works for me as well! Many thks.
